# -*- coding: utf-8 -*-
"""flibrop assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6dXvsjlN91g533A19-SF9dnkqbqTmmA
"""

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

from keras.models import Sequential, load_model
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense, Dropout, Activation
from keras.preprocessing.image import ImageDataGenerator

#

"""Adding Layers and intializing CNN"""

model = Sequential()
model.add(Convolution2D(32, (3, 3), input_shape = (64, 64, 3)))

model.add(Activation('relu'))

model.add(Convolution2D(32, (3, 3)))

model.add(Activation('relu'))

model.add(MaxPooling2D(pool_size=(2,2)))



model.add(Flatten())

model.add(Dense(units=128,activation='relu'))

model.add(Dense(units=1,activation='sigmoid'))



"""Fitting the CNN to the images and Data Augmentation"""

train_datagen = ImageDataGenerator(rescale=1./255, shear_range=0.2, zoom_range=0.2, horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory('/content/drive/My Drive/Amazon_webscraping/Train',target_size=(64,64),batch_size=32,class_mode='binary')

test_set = train_datagen.flow_from_directory('/content/drive/My Drive/Amazon_webscraping/Test',target_size=(64,64),batch_size=32,class_mode='binary')

"""intiating optimizer and configure parameters"""

opt = keras.optimizers.RMSprop(learning_rate=0.0001, decay=1e-6)

"""Compile the model"""

model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

print(model.summary())

"""Training the Model"""

history = model.fit(training_set, steps_per_epoch=4000, epochs = 3, validation_data=test_set,shuffle=True)

model.save("amazon_product_classification")



